### ISSUE TITLE
Form: "Settings" don't open "Form settings" window

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-paris#63]
After clicking to form "Settings" button --> "Settings" option dissapear and don't open "Form settings" window.

![screen shot 2015-10-29 at 10 05 50](https://cloud.githubusercontent.com/assets/13623224/10813083/f0d93198-7e24-11e5-9a1e-eca53690890c.png)

**Comment by kaspar-naaber** [comment]
Fixed: bf00a59f3cb973cbba62dbbb406c26fda20b2f5a

**Comment by SSirjes** [comment]
Seems that it's not working: http://g.recordit.co/ynt051k6Ov.gif

**Comment by SSirjes** [comment]
Everything work now correctly
