### ISSUE TITLE
Dark schema: form settings icon, text stand not good out

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-paris#69]
![screen shot 2016-01-13 at 15 41 03](https://cloud.githubusercontent.com/assets/13623224/12295799/1e9d3cb4-ba0c-11e5-9976-179815d42702.png)

**Comment by kaspar-naaber** [comment]
Accidentally closed wrong issue witht he commit. But this issue is fixed from the CMS side and will resolve after the CMS update.
