### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by hennrunnel** [Voog/design-paris#79]

**Comment by hennrunnel** [comment]
- [ ] Main colors võiks muuta ka blogi listingu pealkirjade värvi. Kui see mingit tagasilööki just ei anna, võiks headeri taustavärv 

- [ ] Lisa eraldi headeri taustavärvi kontroller

- [ ] Võiks saada muuta blog listingu elementide stiile-suurusi esilehel. Vt Barcelona ja Sapporo lahendusi.

- [ ] Alalehel viibides võiks saada “Content” grupis muuta ka “Submenu” stiile. Alternatiiv on

**Comment by SSirjes** [comment]
* [ ] **Header - Title --> text decoration applies to header slogan placeholder**

_Video, what happns: http://www.giphy.com/gifs/l46C6BJirzH4VUeOs_

**Comment by SSirjes** [comment]
* [ ] Header - Main menu - Hover color don't apply do language 
_Video: http://www.giphy.com/gifs/3o6gEeOmUzwZKn1EqI_
